### ISSUE TITLE
Propose

### ISSUE THREAD

**Issue by lorenzogentile404** [TarasKuzyo/LaTeXpkges#18]
Hello, I am considering to modify the script to do the same thing with macros (delete from the file macros that have not been used). I believe the same approach should work, as long as you change the regular expression to identify macros instead of packages and then you should always end up in the "Build failed" case. Do you know if there is already something like that available around?

**Comment by pauloney** [comment]
This is extremely hard Lorenzo, and there are two main reasons for that. 

Fo\irts while most LaTeX source files would contain a few, as in a dozen or so, LaTeX packages, in general they contain many, many more macros, sometimes in the hundreds -- which will, in turn, require a very very long processing time. 

The other is that while  the `\usepackage` commands are somewhat simple, well known, and easier to deal with, a set of macros definition is far more complex. You can play with them. It is easy to cook a file with 2 blocks of macros that you can remove "pairs" of macros but NOT the macros individually. So in order to do a real monimization of the file you would have to play with removing "pairs", "triples", ...

The only feasible approach seems to be -- parsing the sources for usage of one particular macro and then removing it and testing. The parsing can be done very quickly and so the selection of macros. This works well for most files out there. I'll incorporate it in the code soon.
